version: '3.8'

services:

  postgres-auth:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=sawit_auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - sawit-network

#  postgres-pembayaran:
#    image: postgres:16-alpine
#    ports:
#      - "5434:5432"
#    environment:
#      - POSTGRES_DB=sawit_pembayaran
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=root
#    networks:
#      - sawit-network

  auth-service:
    build:
      context: ../authentication_manajemen_akun
    ports:
      - "8081:8081"
    depends_on:
      - postgres-auth
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auth:5432/sawit_auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - sawit-network

#  pembayaran-service:
#    build:
#      context: ../ManajemenPembayaran
#    ports:
#      - "8085:8085"
#    depends_on:
#      - postgres-pembayaran
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-pembayaran:5432/sawit_pembayaran
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=root
#    networks:
#      - sawit-network

  api-gateway:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
#      - pembayaran-service
    networks:
      - sawit-network

networks:
  sawit-network:
    driver: bridge