server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:5173'
              - 'http://127.0.0.1:5173'
              - 'https://mysawit-frontend-2d6fbc97d3fe.herokuapp.com'
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth-service/**
          filters:
            - AuthenticationFilter
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}

        - id: manajemen-kebun-sawit-service
          uri: http://manajemen-kebun-sawit-service:8082
          predicates:
            - Path=/manajemen-kebun-sawit-service/**
          filters:
            - AuthenticationFilter
            - RewritePath=/manajemen-kebun-sawit-service/(?<segment>.*), /$\{segment}

        - id: manajemen-hasil-panen-sawit-service
          uri: http://manajemen-hasil-panen-sawit-service:8083
          predicates:
            - Path=/manajemen-hasil-panen-sawit-service/**
          filters:
            - AuthenticationFilter
            - RewritePath=/manajemen-hasil-panen-sawit-service/(?<segment>.*), /$\{segment}

        - id: pengiriman-hasil-panen-sawit-service
          uri: http://pengiriman-hasil-panen-sawit-service:8084
          predicates:
            - Path=/pengiriman-hasil-panen-sawit-service/**
          filters:
            - AuthenticationFilter
            - RewritePath=/pengiriman-hasil-panen-sawit-service/(?<segment>.*), /$\{segment}

        - id: pembayaran-service
          uri: http://pembayaran-service:8085
          predicates:
            - Path=/pembayaran-service/**
          filters:
            - AuthenticationFilter
            - RewritePath=/pembayaran-service/(?<segment>.*), /$\{segment}

jwt:
  secret: ${JWT_SECRET}
