server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:5173'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: manajemen-kebun-sawit-service
          uri: http://manajemen-kebun-sawit-service:8082
          predicates:
            Path=/kebun-sawit/**
          filters:
            - AuthenticationFilter
            - RewritePath=/kebun-sawit/(?<segment>.*), /$\{segment}

        - id: pembayaran-service
          uri: http://pembayaran-service:8085
          predicates:
            - Path=/pembayaran/**
          filters:
            - AuthenticationFilter
            - RewritePath=/pembayaran/(?<segment>.*), /$\{segment}

jwt:
  secret: ${JWT_SECRET}